{{- define "k8s.core.serviceAccount" }}
{{- include "k8s.factory.subResource" (list . "k8s.rbac.role" "roles") }}
{{- include "k8s.factory.subResource" (list . "k8s.rbac.binding" "bindings") }}
---
apiVersion: v1
kind: ServiceAccount
{{- include "k8s.template.metadata" . }}
...
{{- end }}