{{- define "k8s.core.secret" }}
---
apiVersion: v1
kind: Secret
{{- include "k8s.template.metadata" . }}
type: {{ coalesce .Values.type .Values.global.secret.type }}
data:
  {{- range $k, $v := .Values.plainText }}
  {{ $k | quote }}: {{ $v | toString | b64enc }}
  {{- end }}
  {{- range $k, $v := .Values.encoded }}
  {{ $k | quote }}: {{ $v }}
  {{- end }}
...
{{- end }}