name: publish helm chart

on:
  push:
    branches:
      - main
      - master
    paths:
      - charts/**
      - library-charts/**

permissions:
  pull-requests: write
  contents: write

jobs:
  detect_changes:
    uses: ptonini-actions/workflows/.github/workflows/runner--paths-filter.yaml@main

  release_please:
    uses: ptonini-actions/workflows/.github/workflows/runner--release-please.yaml@main
    if: github.event_name == 'push'

  build_package:
    uses: ptonini-actions/workflows/.github/workflows/handler--helm-chart.yaml@main
    if: needs.release_please.outputs.paths_released != '[]'
    needs:
      - release_please
    strategy:
      matrix:
        context: ${{ fromJSON(needs.release_please.outputs.paths_released) }}
    with:
      action: build
      context: ${{ matrix.context }}

  publish_package:
    uses: ptonini-actions/workflows/.github/workflows/handler--helm-chart.yaml@main
    needs:
      - build_package
    strategy:
      matrix:
        context: ${{ fromJSON(needs.release_please.outputs.paths_released) }}
    with:
      action: publish
      context: ${{ matrix.context }}
    secrets:
      CHARTMUSEUM_USERNAME: ${{ secrets.CHARTMUSEUM_USERNAME }}
      CHARTMUSEUM_PASSWORD: ${{ secrets.CHARTMUSEUM_PASSWORD }}
